<?php

	$role_info[392] = array (
  'code' => 'goal-ETL-SETTINGS',
  'name' => 
  array (
    'ar' => 'إدارة ترحيل البيانات',
    'en' => 'Data migration management',
  ),
  'menu' => 
  array (
    'need_admin' => false,
    'id' => '392',
    'menu_name_' => 'إدارة ترحيل البيانات',
    'menu_name_ar' => 'إدارة ترحيل البيانات',
    'menu_name_en' => 'Data migration management',
    'page' => 'main.php?Main_Page=fm.php&a=1286&r=392',
    'css' => 'info',
    'icon' => ' icon-392',
    'showme' => true,
    'items' => 
    array (
      105052 => 
      array (
        'id' => '105052',
        'code' => 'f2-a-data_api/qsearch',
        'level' => '1',
        'menu_name_ar' => 'خدمات بيانات',
        'menu_name_en' => 'Data apis',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=DataApi&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105052 bfc-',
      ),
      105073 => 
      array (
        'id' => '105073',
        'code' => 'f2-a-end_point/qsearch',
        'level' => '1',
        'menu_name_ar' => 'نقاط نهاية',
        'menu_name_en' => 'End points',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=EndPoint&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105073 bfc-',
      ),
      105066 => 
      array (
        'id' => '105066',
        'code' => 'f2-a-destination_database/qsearch',
        'level' => '1',
        'menu_name_ar' => 'قواعد بيانات مستهدفة',
        'menu_name_en' => 'destination databases',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=DestinationDatabase&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105066 bfc-',
      ),
      105094 => 
      array (
        'id' => '105094',
        'code' => 'f2-a-mapping_job/qsearch',
        'level' => '1',
        'menu_name_ar' => 'مهمات الترحيل',
        'menu_name_en' => 'Individual Jobs',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=MappingJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105094 bfc-',
      ),
      105080 => 
      array (
        'id' => '105080',
        'code' => 'f2-a-mapping_col/qsearch',
        'level' => '1',
        'menu_name_ar' => 'تقابل الحقول',
        'menu_name_en' => 'columns mapping',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=MappingCol&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105080 bfc-',
      ),
      105038 => 
      array (
        'id' => '105038',
        'code' => 'f2-a-auto_job/qsearch',
        'level' => '1',
        'menu_name_ar' => 'مهام آلية',
        'menu_name_en' => 'automatic jobs',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AutoJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105038 bfc-',
      ),
      105045 => 
      array (
        'id' => '105045',
        'code' => 'f2-a-auto_job_contact/qsearch',
        'level' => '1',
        'menu_name_ar' => 'مسؤولين مهام آلية',
        'menu_name_en' => 'automatic job contacts',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AutoJobContact&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105045 bfc-',
      ),
      105059 => 
      array (
        'id' => '105059',
        'code' => 'f2-a-data_transformation/qsearch',
        'level' => '1',
        'menu_name_ar' => 'التحويلات',
        'menu_name_en' => 'transformations',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=DataTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105059 bfc-',
      ),
      105087 => 
      array (
        'id' => '105087',
        'code' => 'f2-a-mapping_col_transformation/qsearch',
        'level' => '1',
        'menu_name_ar' => 'تحويلات الحقول',
        'menu_name_en' => 'mapping column transformations',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=MappingColTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105087 bfc-',
      ),
      105097 => 
      array (
        'id' => '105097',
        'code' => 'f2-a-collection/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة المجموعات',
        'menu_name_en' => 'Collections administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Collection&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105097 bfc-',
      ),
    ),
    'otherbfs' => 
    array (
      105045 => 
      array (
        'id' => '105045',
        'code' => 'f2-a-auto_job_contact/qsearch',
        'level' => '1',
        'menu_name_ar' => 'مسؤولين مهام آلية',
        'menu_name_en' => 'automatic job contacts',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AutoJobContact&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105045 bfc-',
      ),
      105047 => 
      array (
        'id' => '105047',
        'code' => 'f2-a-data_api/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء خدمة بيانات',
        'menu_name_en' => 'create Data api',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=DataApi&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105047 bfc-',
      ),
      105048 => 
      array (
        'id' => '105048',
        'code' => 'f2-a-data_api/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة خدمات بيانات',
        'menu_name_en' => 'Data apis administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=DataApi&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105048 bfc-',
      ),
      105049 => 
      array (
        'id' => '105049',
        'code' => 'f2-a-data_api/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح خدمة بيانات',
        'menu_name_en' => 'delete Data api',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=DataApi&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105049 bfc-',
      ),
      105050 => 
      array (
        'id' => '105050',
        'code' => 'f2-a-data_api/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل خدمة بيانات',
        'menu_name_en' => 'display details of Data api',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=DataApi&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105050 bfc-',
      ),
      105051 => 
      array (
        'id' => '105051',
        'code' => 'f2-a-data_api/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في خدمات بيانات',
        'menu_name_en' => 'Data apis search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=DataApi&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105051 bfc-',
      ),
      105052 => 
      array (
        'id' => '105052',
        'code' => 'f2-a-data_api/qsearch',
        'level' => '1',
        'menu_name_ar' => 'خدمات بيانات',
        'menu_name_en' => 'Data apis',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=DataApi&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105052 bfc-',
      ),
      105054 => 
      array (
        'id' => '105054',
        'code' => 'f2-a-data_transformation/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create transformation',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=DataTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105054 bfc-',
      ),
      105055 => 
      array (
        'id' => '105055',
        'code' => 'f2-a-data_transformation/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة التحويلات',
        'menu_name_en' => 'transformations administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=DataTransformation&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105055 bfc-',
      ),
      105056 => 
      array (
        'id' => '105056',
        'code' => 'f2-a-data_transformation/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete transformation',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=DataTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105056 bfc-',
      ),
      105057 => 
      array (
        'id' => '105057',
        'code' => 'f2-a-data_transformation/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of transformation',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=DataTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105057 bfc-',
      ),
      105058 => 
      array (
        'id' => '105058',
        'code' => 'f2-a-data_transformation/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في التحويلات',
        'menu_name_en' => 'transformations search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=DataTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105058 bfc-',
      ),
      105059 => 
      array (
        'id' => '105059',
        'code' => 'f2-a-data_transformation/qsearch',
        'level' => '1',
        'menu_name_ar' => 'التحويلات',
        'menu_name_en' => 'transformations',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=DataTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105059 bfc-',
      ),
      105061 => 
      array (
        'id' => '105061',
        'code' => 'f2-a-destination_database/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create destination database',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=DestinationDatabase&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105061 bfc-',
      ),
      105062 => 
      array (
        'id' => '105062',
        'code' => 'f2-a-destination_database/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة قواعد بيانات مستهدفة',
        'menu_name_en' => 'destination databases administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=DestinationDatabase&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105062 bfc-',
      ),
      105063 => 
      array (
        'id' => '105063',
        'code' => 'f2-a-destination_database/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete destination database',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=DestinationDatabase&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105063 bfc-',
      ),
      105064 => 
      array (
        'id' => '105064',
        'code' => 'f2-a-destination_database/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of destination database',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=DestinationDatabase&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105064 bfc-',
      ),
      105065 => 
      array (
        'id' => '105065',
        'code' => 'f2-a-destination_database/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في قواعد بيانات مستهدفة',
        'menu_name_en' => 'destination databases search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=DestinationDatabase&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105065 bfc-',
      ),
      105066 => 
      array (
        'id' => '105066',
        'code' => 'f2-a-destination_database/qsearch',
        'level' => '1',
        'menu_name_ar' => 'قواعد بيانات مستهدفة',
        'menu_name_en' => 'destination databases',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=DestinationDatabase&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105066 bfc-',
      ),
      105068 => 
      array (
        'id' => '105068',
        'code' => 'f2-a-end_point/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء نقطة نهاية',
        'menu_name_en' => 'create End point',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=EndPoint&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105068 bfc-',
      ),
      105069 => 
      array (
        'id' => '105069',
        'code' => 'f2-a-end_point/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة نقاط نهاية',
        'menu_name_en' => 'End points administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=EndPoint&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105069 bfc-',
      ),
      105070 => 
      array (
        'id' => '105070',
        'code' => 'f2-a-end_point/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح نقطة نهاية',
        'menu_name_en' => 'delete End point',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=EndPoint&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105070 bfc-',
      ),
      105071 => 
      array (
        'id' => '105071',
        'code' => 'f2-a-end_point/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل نقطة نهاية',
        'menu_name_en' => 'display details of End point',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=EndPoint&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105071 bfc-',
      ),
      105072 => 
      array (
        'id' => '105072',
        'code' => 'f2-a-end_point/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في نقاط نهاية',
        'menu_name_en' => 'End points search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=EndPoint&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105072 bfc-',
      ),
      105073 => 
      array (
        'id' => '105073',
        'code' => 'f2-a-end_point/qsearch',
        'level' => '1',
        'menu_name_ar' => 'نقاط نهاية',
        'menu_name_en' => 'End points',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=EndPoint&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105073 bfc-',
      ),
      105075 => 
      array (
        'id' => '105075',
        'code' => 'f2-a-mapping_col/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء mapping column',
        'menu_name_en' => 'create mapping column',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=MappingCol&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105075 bfc-',
      ),
      105076 => 
      array (
        'id' => '105076',
        'code' => 'f2-a-mapping_col/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة تقابل الحقول',
        'menu_name_en' => 'columns mapping administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=MappingCol&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105076 bfc-',
      ),
      105077 => 
      array (
        'id' => '105077',
        'code' => 'f2-a-mapping_col/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح mapping column',
        'menu_name_en' => 'delete mapping column',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=MappingCol&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105077 bfc-',
      ),
      105078 => 
      array (
        'id' => '105078',
        'code' => 'f2-a-mapping_col/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل mapping column',
        'menu_name_en' => 'display details of mapping column',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=MappingCol&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105078 bfc-',
      ),
      105079 => 
      array (
        'id' => '105079',
        'code' => 'f2-a-mapping_col/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في تقابل الحقول',
        'menu_name_en' => 'columns mapping search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=MappingCol&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105079 bfc-',
      ),
      105080 => 
      array (
        'id' => '105080',
        'code' => 'f2-a-mapping_col/qsearch',
        'level' => '1',
        'menu_name_ar' => 'تقابل الحقول',
        'menu_name_en' => 'columns mapping',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=MappingCol&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105080 bfc-',
      ),
      105082 => 
      array (
        'id' => '105082',
        'code' => 'f2-a-mapping_col_transformation/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create mapping column transformation',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=MappingColTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105082 bfc-',
      ),
      105083 => 
      array (
        'id' => '105083',
        'code' => 'f2-a-mapping_col_transformation/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة تحويلات الحقول',
        'menu_name_en' => 'mapping column transformations administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=MappingColTransformation&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105083 bfc-',
      ),
      105084 => 
      array (
        'id' => '105084',
        'code' => 'f2-a-mapping_col_transformation/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete mapping column transformation',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=MappingColTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105084 bfc-',
      ),
      105085 => 
      array (
        'id' => '105085',
        'code' => 'f2-a-mapping_col_transformation/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of mapping column transformation',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=MappingColTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105085 bfc-',
      ),
      105086 => 
      array (
        'id' => '105086',
        'code' => 'f2-a-mapping_col_transformation/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في تحويلات الحقول',
        'menu_name_en' => 'mapping column transformations search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=MappingColTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105086 bfc-',
      ),
      105087 => 
      array (
        'id' => '105087',
        'code' => 'f2-a-mapping_col_transformation/qsearch',
        'level' => '1',
        'menu_name_ar' => 'تحويلات الحقول',
        'menu_name_en' => 'mapping column transformations',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=MappingColTransformation&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105087 bfc-',
      ),
      105089 => 
      array (
        'id' => '105089',
        'code' => 'f2-a-mapping_job/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء مهمة ترحيل',
        'menu_name_en' => 'create Individual Job',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=MappingJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105089 bfc-',
      ),
      105090 => 
      array (
        'id' => '105090',
        'code' => 'f2-a-mapping_job/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة مهمات الترحيل',
        'menu_name_en' => 'Individual Jobs administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=MappingJob&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105090 bfc-',
      ),
      105091 => 
      array (
        'id' => '105091',
        'code' => 'f2-a-mapping_job/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح مهمة ترحيل',
        'menu_name_en' => 'delete Individual Job',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=MappingJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105091 bfc-',
      ),
      105092 => 
      array (
        'id' => '105092',
        'code' => 'f2-a-mapping_job/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل مهمة ترحيل',
        'menu_name_en' => 'display details of Individual Job',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=MappingJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105092 bfc-',
      ),
      105093 => 
      array (
        'id' => '105093',
        'code' => 'f2-a-mapping_job/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في مهمات الترحيل',
        'menu_name_en' => 'Individual Jobs search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=MappingJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105093 bfc-',
      ),
      105094 => 
      array (
        'id' => '105094',
        'code' => 'f2-a-mapping_job/qsearch',
        'level' => '1',
        'menu_name_ar' => 'مهمات الترحيل',
        'menu_name_en' => 'Individual Jobs',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=MappingJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105094 bfc-',
      ),
      105096 => 
      array (
        'id' => '105096',
        'code' => 'f2-a-collection/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء مجموعة',
        'menu_name_en' => 'create Collection',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Collection&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105096 bfc-',
      ),
      105097 => 
      array (
        'id' => '105097',
        'code' => 'f2-a-collection/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة المجموعات',
        'menu_name_en' => 'Collections administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Collection&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105097 bfc-',
      ),
      105098 => 
      array (
        'id' => '105098',
        'code' => 'f2-a-collection/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح مجموعة',
        'menu_name_en' => 'delete Collection',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Collection&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105098 bfc-',
      ),
      105099 => 
      array (
        'id' => '105099',
        'code' => 'f2-a-collection/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل مجموعة',
        'menu_name_en' => 'display details of Collection',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Collection&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105099 bfc-',
      ),
      105100 => 
      array (
        'id' => '105100',
        'code' => 'f2-a-collection/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في المجموعات',
        'menu_name_en' => 'Collections search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Collection&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105100 bfc-',
      ),
      105101 => 
      array (
        'id' => '105101',
        'code' => 'f2-a-collection/qsearch',
        'level' => '1',
        'menu_name_ar' => 'المجموعات',
        'menu_name_en' => 'Collections',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Collection&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105101 bfc-',
      ),
      105033 => 
      array (
        'id' => '105033',
        'code' => 'f2-a-auto_job/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create automatic job',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AutoJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105033 bfc-',
      ),
      105034 => 
      array (
        'id' => '105034',
        'code' => 'f2-a-auto_job/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة مهام آلية',
        'menu_name_en' => 'automatic jobs administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=AutoJob&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105034 bfc-',
      ),
      105035 => 
      array (
        'id' => '105035',
        'code' => 'f2-a-auto_job/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete automatic job',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AutoJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105035 bfc-',
      ),
      105036 => 
      array (
        'id' => '105036',
        'code' => 'f2-a-auto_job/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of automatic job',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AutoJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105036 bfc-',
      ),
      105037 => 
      array (
        'id' => '105037',
        'code' => 'f2-a-auto_job/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في مهام آلية',
        'menu_name_en' => 'automatic jobs search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AutoJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105037 bfc-',
      ),
      105038 => 
      array (
        'id' => '105038',
        'code' => 'f2-a-auto_job/qsearch',
        'level' => '1',
        'menu_name_ar' => 'مهام آلية',
        'menu_name_en' => 'automatic jobs',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AutoJob&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105038 bfc-',
      ),
      105040 => 
      array (
        'id' => '105040',
        'code' => 'f2-a-auto_job_contact/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create automatic job contact',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AutoJobContact&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105040 bfc-',
      ),
      105041 => 
      array (
        'id' => '105041',
        'code' => 'f2-a-auto_job_contact/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة مسؤولين مهام آلية',
        'menu_name_en' => 'automatic job contacts administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=AutoJobContact&currmod=etl&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105041 bfc-',
      ),
      105042 => 
      array (
        'id' => '105042',
        'code' => 'f2-a-auto_job_contact/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete automatic job contact',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AutoJobContact&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105042 bfc-',
      ),
      105043 => 
      array (
        'id' => '105043',
        'code' => 'f2-a-auto_job_contact/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of automatic job contact',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AutoJobContact&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105043 bfc-',
      ),
      105044 => 
      array (
        'id' => '105044',
        'code' => 'f2-a-auto_job_contact/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في مسؤولين مهام آلية',
        'menu_name_en' => 'automatic job contacts search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AutoJobContact&currmod=etl',
        'css' => 'bf',
        'icon' => 'bficon-105044 bfc-',
      ),
    ),
    'sub-folders' => 
    array (
    ),
  ),
);